sudo: false
cache:
  directories:
  - .cabal-sandbox
language: haskell
ghc: 7.8
install:
- cabal sandbox init
- cabal install --only-dependencies --enable-tests
script:
- cabal configure --enable-tests && cabal build && cabal test
- cabal run rebuild
deploy:
  provider: s3
  access_key_id:
    secure: Uy5WrAZP5zsf1td8B5I4Vl2BMdh0qxBiftPjc+r3Gkks9VQwyF+3UOUyTyVUQr5xPnd4c5wFDKOKVluXBFSZw8xsqL75G1XR3LRypT5Hx0q3/y5HB/7iEJ/drSRxsDPZb8MunXxHMHJqVxzxvbUTerIoU8xoITiB7qHE6eNen1U=
  secret_access_key:
    secure: l2sywXi9qXjjE9Rk4QoJ+CdxWI00/0qb3E01EokkQd/iNGTdLg0ehDCiNW1ltdQZqWdmJktai5fgij6rPs4l/q5CwqZCEqigS6vC5q0c+Q1wdKAJo5JE2ZJfcLfic2gpVHhT1JUIsZfQURsQi9x/0d41FfmI4aQikDZJJ/XiAaM=
  bucket: dev.forkk.net
  skip_cleanup: true
  local_dir: _site
  upload-dir: $TRAVIS_BRANCH
  endpoint: dev.forkk.net.s3-website-us-east-1.amazonaws.com
  region: US Standard
  on:
    repo: Forkk/forkk.net
    all_branches: true
